apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka-consumer
  name: kafka-consumer
spec:
  ports:
  - name: "5003"
    port: 5003
    targetPort: 5003
    nodePort: 30005
  selector:
    service: kafka-consumer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kafka-consumer
  name: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kafka-consumer
  template:
    metadata:
      labels:
        service: kafka-consumer
    spec:
      containers:
      - image: solondungu/kafka-consumer:latest
        name: kafka-consumer
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name : DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always