apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-producer
  name: location-producer
spec:
  ports:
  - name: "5555"
    port: 5555
    targetPort: 5555
    nodePort: 30003
  selector:
    service: location-producer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-producer
  name: location-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-producer
  template:
    metadata:
      labels:
        service: location-producer
    spec:
      containers:
      - image: ziademad/location-producer:latest
        name: location-producer
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "256m"
        env:
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_URL
      restartPolicy: Always
