# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: location.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='location.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0elocation.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x01\n\x16LocationMessageRequest\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12\x31\n\rcreation_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08latitude\x18\x03 \x01(\x02\x12\x11\n\tlongitude\x18\x04 \x01(\x02\"$\n\x16RetrieveMessageRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"c\n\x17LocationMessageResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tperson_id\x18\x02 \x01(\x05\x12\x12\n\ncoordinate\x18\x03 \x01(\t\x12\x15\n\rcreation_time\x18\x04 \x01(\t2\x88\x01\n\x0fLocationService\x12\x38\n\x03Get\x12\x17.RetrieveMessageRequest\x1a\x18.LocationMessageResponse\x12;\n\x06\x43reate\x12\x17.LocationMessageRequest\x1a\x18.LocationMessageResponseb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_LOCATIONMESSAGEREQUEST = _descriptor.Descriptor(
  name='LocationMessageRequest',
  full_name='LocationMessageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='person_id', full_name='LocationMessageRequest.person_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='creation_time', full_name='LocationMessageRequest.creation_time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='LocationMessageRequest.latitude', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='LocationMessageRequest.longitude', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=183,
)


_RETRIEVEMESSAGEREQUEST = _descriptor.Descriptor(
  name='RetrieveMessageRequest',
  full_name='RetrieveMessageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RetrieveMessageRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=221,
)


_LOCATIONMESSAGERESPONSE = _descriptor.Descriptor(
  name='LocationMessageResponse',
  full_name='LocationMessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='LocationMessageResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='person_id', full_name='LocationMessageResponse.person_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='coordinate', full_name='LocationMessageResponse.coordinate', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='creation_time', full_name='LocationMessageResponse.creation_time', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=322,
)

_LOCATIONMESSAGEREQUEST.fields_by_name['creation_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['LocationMessageRequest'] = _LOCATIONMESSAGEREQUEST
DESCRIPTOR.message_types_by_name['RetrieveMessageRequest'] = _RETRIEVEMESSAGEREQUEST
DESCRIPTOR.message_types_by_name['LocationMessageResponse'] = _LOCATIONMESSAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LocationMessageRequest = _reflection.GeneratedProtocolMessageType('LocationMessageRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONMESSAGEREQUEST,
  '__module__' : 'location_pb2'
  # @@protoc_insertion_point(class_scope:LocationMessageRequest)
  })
_sym_db.RegisterMessage(LocationMessageRequest)

RetrieveMessageRequest = _reflection.GeneratedProtocolMessageType('RetrieveMessageRequest', (_message.Message,), {
  'DESCRIPTOR' : _RETRIEVEMESSAGEREQUEST,
  '__module__' : 'location_pb2'
  # @@protoc_insertion_point(class_scope:RetrieveMessageRequest)
  })
_sym_db.RegisterMessage(RetrieveMessageRequest)

LocationMessageResponse = _reflection.GeneratedProtocolMessageType('LocationMessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONMESSAGERESPONSE,
  '__module__' : 'location_pb2'
  # @@protoc_insertion_point(class_scope:LocationMessageResponse)
  })
_sym_db.RegisterMessage(LocationMessageResponse)



_LOCATIONSERVICE = _descriptor.ServiceDescriptor(
  name='LocationService',
  full_name='LocationService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=325,
  serialized_end=461,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='LocationService.Get',
    index=0,
    containing_service=None,
    input_type=_RETRIEVEMESSAGEREQUEST,
    output_type=_LOCATIONMESSAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='LocationService.Create',
    index=1,
    containing_service=None,
    input_type=_LOCATIONMESSAGEREQUEST,
    output_type=_LOCATIONMESSAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOCATIONSERVICE)

DESCRIPTOR.services_by_name['LocationService'] = _LOCATIONSERVICE

# @@protoc_insertion_point(module_scope)
