name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./modules/connection_api
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ziademad/connection_api:latest
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./modules/location_api
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ziademad/location_api:latest
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./modules/person_api
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ziademad/person_api:latest
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./modules/frontend
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ziademad/frontend:latest
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./modules/kafka
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ziademad/kafka:latest
          
