name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./modules/location-api
          platforms: linux/amd64
          push: true
          tags: ziademad/location-api:latest
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./modules/location-consumer
          platforms: linux/amd64
          push: true
          tags: ziademad/location-consumer:latest
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./modules/location-producer
          platforms: linux/amd64
          push: true
          tags: ziademad/location-producer:latest
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./modules/frontend
          platforms: linux/amd64
          push: true
          tags: ziademad/frontend:latest
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./modules/person-api
          platforms: linux/amd64
          push: true
          tags: ziademad/person-api:latest
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./modules/person-api
          platforms: linux/amd64
          push: true
          tags: ziademad/person-api:latest
          
